### ISSUE TITLE
FROM ubuntu:16.04 (LTS release is outdated)

### ISSUE THREAD

**Issue by kingdonb** [criteo/kerberos-docker#3]
I wonder if this represents a major overhaul

I just noticed during "make install" that it was pulling down ubuntu:16.04, and I wonder if you've already started work on an upgraded version?

**Comment by glegoux** [comment]
Hello,

Thanks a lot for this feedback, I could migrate to ubuntu 18.04 at least. But in my mind, originally I wanted to follow Travis versioning and only LTS.

Currently, Travis follows ubuntu 16.04:
https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment   

Ubuntu 16.04 is not deprecated yet:
https://wiki.ubuntu.com/Releases  

But I understand the need to have a more recent version, and I agree, that Travis is a bit late, if I follow correctly?

Perhaps, I will provide a more recent version for Ubuntu, to follow better the latest version than Travis. But as I have some unit tests between the host machine and Docker containers, I hope that not put some issues. I will investigate.

Don't hesitate to propose a pull request :).

**Comment by kingdonb** [comment]
That's a perfectly reasonable rationale, follow the leader.  I can't say that I have a specific need for it, I may not end up using the KDC container that you provided for anything serious either.  Over time, the need will be more obvious as LTS releases are eventually deprecated, but for now 16.04 (an LTS release) is still supported, so it's not like you're running on an obsolete stack.

Systemd may provide new challenges.  I won't go into it any deeper as I haven't explored it, and you can feel free to close this if the answer is "not at this time."  At any rate I have learned a great deal from briefly implementing my own KRB5 domain with your containerized example, and this opened up a great number of possibilities for securing my disposable Kubernetes environments that I am provisioning to test K8s apps on.  Those environments may need to work without external support in order to be useful, and they will in most cases be on the public internet with access to instance roles that can provision new infra nodes, so need to take security as seriously as any production service.

If I am able to make this work as a Helm chart or Kubernetes manifests, I will certainly try to find a way to contribute them back!

**Comment by glegoux** [comment]
Now, it uses Ubuntu 22.04 LTS with GitHub Actions.
